name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Copy custom folder
      run: |
          sudo mkdir -p /home/user/spark-app
          cp -r app/* /home/user/spark-app
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: abhijitdhamne/spark-pi:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
